function createfigure1(X1, YMatrix1)
%CREATEFIGURE2(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-Jun-2018 15:00:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'LineWidth',2);
set(semilogy1(1),'DisplayName','OFDM-84','LineStyle','--');
set(semilogy1(2),'DisplayName','FBMC-100','Marker','o');

% Create xlabel
xlabel('$E_b/N_0$','Interpreter','latex');

% Create ylabel
ylabel('BER','Interpreter','latex');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14,'TickLabelInterpreter','latex','YMinorTick','on',...
    'YScale','log');
% Create legend
legend(axes1,'show');

